/**
 * Briefings: generated by Claude using the user's current data.
 * 4 types — morning, eod, weekly, monthly.
 *
 * Called by /api/cron/brief, which is hit by Supabase pg_cron at scheduled times.
 */
import Anthropic from "@anthropic-ai/sdk";
import type { SupabaseClient } from "@supabase/supabase-js";
import { NALDOS_GOALS, YLL_SEASONALITY_NOTE } from "@/lib/prompts";
import { summarizeFinance } from "@/lib/plaid";
import { HEALTH_GOALS } from "@/lib/health";

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
const MODEL = "claude-sonnet-4-6";

// Naldo's local timezone. Render runs in UTC, so every "today" boundary and
// event-time display has to be tz-aware or the briefings drift by 4h (EDT) / 5h (EST).
const TIMEZONE = "America/New_York";

/**
 * Returns the UTC instant that equals 00:00 local-tz on the date `now` falls on
 * in `tz`. e.g. now = 2026-05-04T10:30:00Z, tz = America/New_York →
 * 2026-05-04T04:00:00Z (= midnight EDT). DST-safe within a day.
 */
function startOfDayInTz(now: Date, tz: string): Date {
  const ymd = new Intl.DateTimeFormat("en-CA", {
    timeZone: tz,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(now);
  // Probe at noon UTC of that date — guaranteed to land in the same tz day.
  const probe = new Date(`${ymd}T12:00:00Z`);
  const hourInTz = parseInt(
    new Intl.DateTimeFormat("en-US", {
      timeZone: tz,
      hour: "numeric",
      hour12: false,
    }).format(probe),
    10
  );
  return new Date(probe.getTime() - hourInTz * 60 * 60 * 1000);
}

// $500K target lives here so it's defined exactly once across briefings + UI.
const REVENUE_TARGET_USD = 500000;

function summarizeBusiness(input: {
  ytdWonRows: { monetary_value?: number | null }[];
  openRows: { monetary_value?: number | null }[];
  weekWonRows: { monetary_value?: number | null }[];
  newLeadsThisWeek: number;
  now: Date;
}): BriefContext["business"] | undefined {
  const { ytdWonRows, openRows, weekWonRows, newLeadsThisWeek, now } = input;
  const hasAny =
    ytdWonRows.length > 0 ||
    openRows.length > 0 ||
    weekWonRows.length > 0 ||
    newLeadsThisWeek > 0;
  if (!hasAny) return undefined;

  const sum = (rows: { monetary_value?: number | null }[]) =>
    rows.reduce((s, r) => s + (Number(r.monetary_value) || 0), 0);

  const revenueYtd = sum(ytdWonRows);
  const pipelineValue = sum(openRows);
  const wonThisWeekValue = sum(weekWonRows);

  const yearStart = new Date(now.getFullYear(), 0, 1).getTime();
  const dayOfYear = Math.max(
    1,
    Math.round((now.getTime() - yearStart) / 86400000)
  );
  const yearEnd = new Date(now.getFullYear() + 1, 0, 1).getTime();
  const daysLeftInYear = Math.max(
    1,
    Math.round((yearEnd - now.getTime()) / 86400000)
  );

  const dailyRunRate = revenueYtd / dayOfYear;
  const eoyProjection = dailyRunRate * 365;
  const revenueRemaining = Math.max(0, REVENUE_TARGET_USD - revenueYtd);
  const revenuePctToTarget = revenueYtd / REVENUE_TARGET_USD;
  const requiredDailyToHitTarget = revenueRemaining / daysLeftInYear;

  return {
    revenueYtd: Math.round(revenueYtd),
    revenueTarget: REVENUE_TARGET_USD,
    revenueRemaining: Math.round(revenueRemaining),
    revenuePctToTarget: +revenuePctToTarget.toFixed(3),
    dailyRunRate: Math.round(dailyRunRate),
    eoyProjection: Math.round(eoyProjection),
    pipelineValue: Math.round(pipelineValue),
    openCount: openRows.length,
    wonThisWeekCount: weekWonRows.length,
    wonThisWeekValue: Math.round(wonThisWeekValue),
    newLeadsThisWeek,
    daysLeftInYear,
    requiredDailyToHitTarget: Math.round(requiredDailyToHitTarget),
  };
}

/** YYYY-MM-DD in `tz` — used to bucket health metrics by Naldo's local day. */
function dayKeyTz(iso: string, tz: string): string {
  return new Intl.DateTimeFormat("en-CA", {
    timeZone: tz,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(new Date(iso));
}

type HealthRow = {
  metric_type: string;
  value: number;
  unit: string | null;
  recorded_at: string;
};

/**
 * Boil ~14 days of raw health samples down to the snapshot the brief needs.
 * Returns undefined when there's nothing — caller leaves `ctx.health` blank
 * and the prompt skips the section entirely.
 */
function summarizeHealth(
  rows: HealthRow[],
  now: Date
): BriefContext["health"] | undefined {
  if (rows.length === 0) return undefined;

  const today = dayKeyTz(now.toISOString(), TIMEZONE);
  const buckets = new Map<string, Map<string, number[]>>(); // type → day → values
  for (const r of rows) {
    const day = dayKeyTz(r.recorded_at, TIMEZONE);
    if (!buckets.has(r.metric_type)) buckets.set(r.metric_type, new Map());
    const m = buckets.get(r.metric_type)!;
    if (!m.has(day)) m.set(day, []);
    m.get(day)!.push(r.value);
  }

  function lastNDayKeys(n: number): string[] {
    const out: string[] = [];
    for (let i = 0; i < n; i++) {
      const d = new Date(now.getTime() - i * 86400000);
      out.push(dayKeyTz(d.toISOString(), TIMEZONE));
    }
    return out;
  }

  // Steps — sum per day
  const stepsBuckets = buckets.get("steps");
  const stepsToday = stepsBuckets?.get(today)?.reduce((s, v) => s + v, 0) ?? 0;
  const stepsLast7 = lastNDayKeys(7).map(
    (k) => stepsBuckets?.get(k)?.reduce((s, v) => s + v, 0) ?? 0
  );
  const stepsAvg7d =
    stepsLast7.length > 0
      ? stepsLast7.reduce((s, v) => s + v, 0) / stepsLast7.length
      : 0;

  // Sleep — last meaningful night, plus 7-day avg of nights with data
  const sleepBuckets = buckets.get("sleep_hours");
  let sleepLastNightHours: number | null = null;
  for (const k of lastNDayKeys(7)) {
    const vals = sleepBuckets?.get(k);
    if (vals && vals.length > 0) {
      sleepLastNightHours = Math.max(...vals);
      break;
    }
  }
  const sleepDays = lastNDayKeys(7)
    .map((k) => sleepBuckets?.get(k))
    .filter((v): v is number[] => !!v && v.length > 0)
    .map((v) => Math.max(...v));
  const sleepAvg7dHours =
    sleepDays.length > 0
      ? sleepDays.reduce((s, v) => s + v, 0) / sleepDays.length
      : null;

  // Weight — most recent + delta vs ~7 days ago (closest reading)
  const weightRows = rows
    .filter((r) => r.metric_type === "weight")
    .sort((a, b) => b.recorded_at.localeCompare(a.recorded_at));
  const weightLatest =
    weightRows.length > 0
      ? {
          value: weightRows[0].value,
          unit: weightRows[0].unit,
          recorded_at: weightRows[0].recorded_at,
        }
      : null;
  let weightDelta7d: number | null = null;
  if (weightLatest) {
    const target = now.getTime() - 7 * 86400000;
    const ref = weightRows
      .map((r) => ({
        v: r.value,
        diff: Math.abs(new Date(r.recorded_at).getTime() - target),
      }))
      .sort((a, b) => a.diff - b.diff)[0];
    if (ref && ref.diff < 5 * 86400000) {
      weightDelta7d = +(weightLatest.value - ref.v).toFixed(1);
    }
  }

  // Workouts — count days with any workout_minutes > 0 in the last 7 days
  const workoutBuckets = buckets.get("workout_minutes");
  let workoutDays7d = 0;
  let workoutMinutes7d = 0;
  for (const k of lastNDayKeys(7)) {
    const vals = workoutBuckets?.get(k);
    if (vals && vals.length > 0) {
      const sum = vals.reduce((s, v) => s + v, 0);
      if (sum > 0) {
        workoutDays7d++;
        workoutMinutes7d += sum;
      }
    }
  }

  // Resting heart rate — most recent reading
  const rhrRow = rows.find((r) => r.metric_type === "resting_heart_rate");

  return {
    weightLatest,
    weightDelta7d,
    stepsToday,
    stepsAvg7d: Math.round(stepsAvg7d),
    sleepLastNightHours,
    sleepAvg7dHours: sleepAvg7dHours ? +sleepAvg7dHours.toFixed(1) : null,
    workoutDays7d,
    workoutMinutes7d: Math.round(workoutMinutes7d),
    rhrLatest: rhrRow ? Math.round(rhrRow.value) : null,
  };
}

/**
 * Extract long-term memories from the last 24h of user messages.
 * Called from EOD brief. Idempotent — skips facts already in memories.
 */
export async function extractAndSaveMemories(
  supabase: SupabaseClient,
  userId: string
): Promise<{ subject: string; fact: string }[]> {
  const yesterday = new Date(Date.now() - 24 * 60 * 60 * 1000);

  const [{ data: messages }, { data: existing }] = await Promise.all([
    supabase
      .from("chat_messages")
      .select("content, channel")
      .eq("user_id", userId)
      .eq("role", "user")
      .gte("created_at", yesterday.toISOString())
      .order("created_at"),
    supabase
      .from("memories")
      .select("subject, fact")
      .eq("user_id", userId)
      .eq("active", true),
  ]);

  if (!messages || messages.length === 0) return [];

  const existingList = (existing ?? [])
    .map((m) => `- [${m.subject}] ${m.fact}`)
    .join("\n");
  const messagesList = messages
    .map((m) => `[${m.channel ?? "?"}] ${m.content}`)
    .join("\n");

  const completion = await anthropic.messages.create({
    model: MODEL,
    max_tokens: 800,
    system: `You extract long-term factual memories from a user's chat messages. Long-term means: preferences, rules, biographical details, contact facts — things worth remembering across sessions.

NOT memories: one-off tasks, reminders, ephemeral context, transient feelings, things that already exist in current memory.

Output ONLY a JSON array. Each item: {"subject": "user" or a contact name, "fact": "the fact in one sentence"}.

If nothing new is worth remembering, output [].`,
    messages: [
      {
        role: "user",
        content: `EXISTING MEMORIES (don't duplicate):\n${existingList || "(none yet)"}\n\nUSER MESSAGES (last 24h):\n${messagesList}\n\nExtract new memories as JSON array.`,
      },
    ],
  });

  const block = completion.content[0];
  if (!block || block.type !== "text") return [];

  // Parse JSON array — Claude may wrap it in prose
  const match = block.text.match(/\[[\s\S]*\]/);
  if (!match) return [];

  let facts: unknown;
  try {
    facts = JSON.parse(match[0]);
  } catch {
    return [];
  }
  if (!Array.isArray(facts)) return [];

  const inserted: { subject: string; fact: string }[] = [];
  for (const f of facts) {
    if (
      !f ||
      typeof f !== "object" ||
      typeof (f as Record<string, unknown>).subject !== "string" ||
      typeof (f as Record<string, unknown>).fact !== "string"
    ) {
      continue;
    }
    const subject = (f as { subject: string }).subject.trim();
    const fact = (f as { fact: string }).fact.trim();
    if (!subject || !fact) continue;

    const { error } = await supabase.from("memories").insert({
      user_id: userId,
      subject,
      fact,
      active: true,
    });
    if (!error) inserted.push({ subject, fact });
  }

  return inserted;
}

export type BriefType = "morning" | "eod" | "weekly" | "monthly";

export type BriefContext = {
  type: BriefType;
  todaysTasks: { title: string; priority: string; flagged: boolean }[];
  flaggedAvoidance: { title: string; flagged_at: string; days_flagged: number }[];
  todaysEvents: { title: string; starts_at: string }[];
  upcomingEvents: { title: string; starts_at: string }[];
  pendingReminders: number;
  recentCaptures: { title: string | null; source: string }[];
  recentMemories: { subject: string; fact: string }[];
  // Health snapshot (Apple Health → /api/health/ingest). Empty when nothing synced yet.
  health?: {
    weightLatest: { value: number; unit: string | null; recorded_at: string } | null;
    weightDelta7d: number | null;            // lbs change vs 7d-ago weight, null if missing
    stepsToday: number;
    stepsAvg7d: number;
    sleepLastNightHours: number | null;
    sleepAvg7dHours: number | null;
    workoutDays7d: number;
    workoutMinutes7d: number;
    rhrLatest: number | null;
  };
  // Business snapshot (GoHighLevel → gohighlevel_opportunities). Empty when nothing synced yet.
  business?: {
    revenueYtd: number;
    revenueTarget: number;
    revenueRemaining: number;
    revenuePctToTarget: number;            // 0..1
    dailyRunRate: number;
    eoyProjection: number;
    pipelineValue: number;
    openCount: number;
    wonThisWeekCount: number;
    wonThisWeekValue: number;
    newLeadsThisWeek: number;
    daysLeftInYear: number;
    requiredDailyToHitTarget: number;
  };
  // Finance snapshot (Plaid → plaid_accounts + plaid_transactions). Empty when nothing connected.
  finance?: {
    cashTotal: number;
    debtTotal: number;
    debtPaidOff: number;
    debtBaseline: number;
    debtPctPaid: number;                    // 0..1
    netLiquid: number;
    burn30d: number;
    income30d: number;
    netFlow30d: number;
  };
  // Window-specific data
  weekStats?: {
    tasksCompleted: number;
    captures: number;
    remindersFired: number;
  };
  monthStats?: {
    tasksCompleted: number;
    avgCapturesPerDay: number;
    longestStreak: number; // days with at least one task done
  };
};

export async function gatherBriefContext(
  supabase: SupabaseClient,
  userId: string,
  type: BriefType
): Promise<BriefContext> {
  const now = new Date();
  // Day boundaries in Naldo's local tz, NOT server UTC. Without this, the
  // morning brief at 6:30am EDT (10:30 UTC) treats "today" as UTC, so events
  // between 8pm–midnight EDT get dropped from today's events.
  const startOfToday = startOfDayInTz(now, TIMEZONE);
  const endOfToday = new Date(startOfToday.getTime() + 24 * 60 * 60 * 1000);
  const oneWeekAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
  const oneMonthAgo = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);

  const yearStartIso = new Date(now.getFullYear(), 0, 1).toISOString();

  const [
    tasks,
    avoidance,
    todayEvents,
    upcomingEvents,
    reminders,
    captures,
    memories,
    health,
    ghlYtdWon,
    ghlOpen,
    ghlWeekWon,
    ghlWeekNew,
    plaidAccounts,
    plaidTx,
  ] = await Promise.all([
    supabase
      .from("tasks")
      .select("title, priority, flagged, status")
      .eq("user_id", userId)
      .neq("status", "done")
      .order("priority")
      .limit(20),
    supabase
      .from("avoidance_items")
      .select("title, flagged_at")
      .eq("user_id", userId)
      .eq("flagged", true)
      .eq("completed", false)
      .order("flagged_at"),
    supabase
      .from("calendar_events")
      .select("title, starts_at")
      .eq("user_id", userId)
      .gte("starts_at", startOfToday.toISOString())
      .lt("starts_at", endOfToday.toISOString())
      .order("starts_at"),
    supabase
      .from("calendar_events")
      .select("title, starts_at")
      .eq("user_id", userId)
      .gte("starts_at", endOfToday.toISOString())
      .lt(
        "starts_at",
        new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000).toISOString()
      )
      .order("starts_at")
      .limit(5),
    supabase
      .from("reminders")
      .select("*", { count: "exact", head: true })
      .eq("user_id", userId)
      .eq("status", "active"),
    supabase
      .from("captures")
      .select("title, source")
      .eq("user_id", userId)
      .gte("created_at", oneWeekAgo.toISOString())
      .order("created_at", { ascending: false })
      .limit(15),
    supabase
      .from("memories")
      .select("subject, fact")
      .eq("user_id", userId)
      .eq("active", true)
      .limit(20),
    // Last 14 days of health metrics — enough for today vs 7-day-avg deltas.
    supabase
      .from("health_metrics")
      .select("metric_type, value, unit, recorded_at")
      .eq("user_id", userId)
      .gte("recorded_at", new Date(now.getTime() - 14 * 86400000).toISOString())
      .order("recorded_at", { ascending: false })
      .limit(2000),

    // GoHighLevel — won deals YTD (revenue toward $500K target)
    supabase
      .from("gohighlevel_opportunities")
      .select("monetary_value, ghl_status_changed_at, ghl_updated_at")
      .eq("user_id", userId)
      .eq("status", "won")
      .or(
        `ghl_status_changed_at.gte.${yearStartIso},and(ghl_status_changed_at.is.null,ghl_updated_at.gte.${yearStartIso})`
      ),

    // Open opportunities — current pipeline value
    supabase
      .from("gohighlevel_opportunities")
      .select("monetary_value")
      .eq("user_id", userId)
      .eq("status", "open"),

    // Won this week
    supabase
      .from("gohighlevel_opportunities")
      .select("monetary_value")
      .eq("user_id", userId)
      .eq("status", "won")
      .gte("ghl_status_changed_at", oneWeekAgo.toISOString()),

    // New leads this week (any status, freshly created in last 7 days)
    supabase
      .from("gohighlevel_opportunities")
      .select("external_id", { count: "exact", head: true })
      .eq("user_id", userId)
      .gte("ghl_created_at", oneWeekAgo.toISOString()),

    // Plaid accounts — current balances for cash + debt
    supabase
      .from("plaid_accounts")
      .select("type, current_balance, is_debt, is_active")
      .eq("user_id", userId)
      .eq("is_active", true),

    // Plaid transactions in last 30 days — for income/burn
    supabase
      .from("plaid_transactions")
      .select("amount, date")
      .eq("user_id", userId)
      .gte("date", new Date(now.getTime() - 30 * 86400000).toISOString().slice(0, 10))
      .limit(5000),
  ]);

  const ctx: BriefContext = {
    type,
    todaysTasks: (tasks.data ?? [])
      .filter((t) => t.status === "today")
      .map((t) => ({ title: t.title, priority: t.priority, flagged: t.flagged })),
    flaggedAvoidance: (avoidance.data ?? []).map((a) => {
      const days = Math.floor(
        (now.getTime() - new Date(a.flagged_at).getTime()) /
          (24 * 60 * 60 * 1000)
      );
      return { title: a.title, flagged_at: a.flagged_at, days_flagged: days };
    }),
    todaysEvents: todayEvents.data ?? [],
    upcomingEvents: upcomingEvents.data ?? [],
    pendingReminders: reminders.count ?? 0,
    recentCaptures: captures.data ?? [],
    recentMemories: memories.data ?? [],
    health: summarizeHealth(health.data ?? [], now),
    business: summarizeBusiness({
      ytdWonRows: ghlYtdWon.data ?? [],
      openRows: ghlOpen.data ?? [],
      weekWonRows: ghlWeekWon.data ?? [],
      newLeadsThisWeek: ghlWeekNew.count ?? 0,
      now,
    }),
    finance: ((plaidAccounts.data ?? []).length > 0
      ? summarizeFinance(
          (plaidAccounts.data ?? []).map((a) => ({
            type: a.type as string | null,
            current_balance: a.current_balance as number | null,
            is_debt: a.is_debt as boolean | null,
            is_active: a.is_active as boolean | null,
          })),
          (plaidTx.data ?? []).map((t) => ({
            amount: Number(t.amount),
            date: t.date as string | null,
          }))
        )
      : undefined) as BriefContext["finance"],
  };

  if (type === "weekly") {
    const [tasksCompleted, capturesCount, remindersFired] = await Promise.all([
      supabase
        .from("tasks")
        .select("*", { count: "exact", head: true })
        .eq("user_id", userId)
        .eq("status", "done")
        .gte("completed_at", oneWeekAgo.toISOString()),
      supabase
        .from("captures")
        .select("*", { count: "exact", head: true })
        .eq("user_id", userId)
        .gte("created_at", oneWeekAgo.toISOString()),
      supabase
        .from("reminder_logs")
        .select("*", { count: "exact", head: true })
        .eq("user_id", userId)
        .gte("fired_at", oneWeekAgo.toISOString()),
    ]);
    ctx.weekStats = {
      tasksCompleted: tasksCompleted.count ?? 0,
      captures: capturesCount.count ?? 0,
      remindersFired: remindersFired.count ?? 0,
    };
  }

  if (type === "monthly") {
    const [tasksCompleted, capturesCount] = await Promise.all([
      supabase
        .from("tasks")
        .select("*", { count: "exact", head: true })
        .eq("user_id", userId)
        .eq("status", "done")
        .gte("completed_at", oneMonthAgo.toISOString()),
      supabase
        .from("captures")
        .select("created_at")
        .eq("user_id", userId)
        .gte("created_at", oneMonthAgo.toISOString()),
    ]);
    const days = new Set(
      (capturesCount.data ?? []).map((c) =>
        new Date(c.created_at).toISOString().slice(0, 10)
      )
    );
    ctx.monthStats = {
      tasksCompleted: tasksCompleted.count ?? 0,
      avgCapturesPerDay: (capturesCount.data?.length ?? 0) / 30,
      longestStreak: days.size, // approximation — days with activity
    };
  }

  return ctx;
}

export async function generateBriefText(
  ctx: BriefContext,
  timezone: string = TIMEZONE
): Promise<string> {
  const now = new Date();
  const localTime = now.toLocaleString("en-US", {
    timeZone: timezone,
    weekday: "long",
    month: "long",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });

  const systemPrompt = buildBriefSystemPrompt(ctx.type);
  const userPrompt = buildBriefUserPrompt(ctx, localTime);

  const completion = await anthropic.messages.create({
    model: MODEL,
    max_tokens: 600,
    system: systemPrompt,
    messages: [{ role: "user", content: userPrompt }],
  });

  const block = completion.content[0];
  return block && block.type === "text" ? block.text : "";
}

function buildBriefSystemPrompt(type: BriefType): string {
  const base = `You are Brain, Naldo's AI assistant. Generate a brief in his "straight-talking coach" voice — direct, honest, references his goals when he's drifting.

NALDO'S 2026 GOALS:
${NALDOS_GOALS}

YLL BUSINESS CONTEXT:
${YLL_SEASONALITY_NOTE}

Format guidelines:
- Use emojis sparingly: 🌅 morning, 🌙 evening, 📅 weekly, 🎯 monthly, ✅ wins, 🤔 pushback
- Keep it tight — Naldo is busy. Aim for 4-6 short lines.
- Bold key numbers and action items with *asterisks* (WhatsApp-flavored markdown).
- End with one clear "today's focus" / "this week's focus" / "next month's focus" line.`;

  if (type === "morning") {
    return `${base}

This is a MORNING BRIEFING — sent at 6:30 AM via WhatsApp.
Goal: orient him for the day. Today's events, today's tasks, anything he's avoiding, anything urgent.
Tone: punchy. He's about to start the day. Don't be philosophical.`;
  }
  if (type === "eod") {
    return `${base}

This is an END-OF-DAY summary — sent at 10 PM via WhatsApp.
Goal: reflect on what shipped today, what's still flagged, set up tomorrow's first move.
Tone: encouraging but honest. Call out if he ducked something.`;
  }
  if (type === "weekly") {
    return `${base}

This is a SUNDAY WEEKLY REVIEW — sent at 7 PM Sundays.
Goal: pattern-recognize the week. Wins, drift, what to adjust.
Tone: coach-like. Reference goals if he drifted.`;
  }
  return `${base}

This is a MONTHLY PROGRESS CHECK — sent on the 1st at 7 PM.
Goal: zoom out. Velocity check against 2026 goals. What's working / what to adjust / next month focus.
Tone: strategic. Be direct about where he stood vs target.`;
}

function buildBriefUserPrompt(ctx: BriefContext, localTime: string): string {
  const lines: string[] = [`Current time: ${localTime}`, ""];

  lines.push(`PENDING REMINDERS: ${ctx.pendingReminders}`);

  if (ctx.todaysEvents.length > 0) {
    lines.push("", "TODAY'S EVENTS:");
    for (const e of ctx.todaysEvents) {
      const t = new Date(e.starts_at).toLocaleTimeString("en-US", {
        timeZone: TIMEZONE,
        hour: "numeric",
        minute: "2-digit",
      });
      lines.push(`- ${t}: ${e.title}`);
    }
  }

  if (ctx.upcomingEvents.length > 0) {
    lines.push("", "UPCOMING (next 7 days):");
    for (const e of ctx.upcomingEvents) {
      const d = new Date(e.starts_at).toLocaleDateString("en-US", {
        timeZone: TIMEZONE,
        weekday: "short",
        month: "short",
        day: "numeric",
      });
      const t = new Date(e.starts_at).toLocaleTimeString("en-US", {
        timeZone: TIMEZONE,
        hour: "numeric",
        minute: "2-digit",
      });
      lines.push(`- ${d} ${t}: ${e.title}`);
    }
  }

  if (ctx.todaysTasks.length > 0) {
    lines.push("", "TASKS MARKED TODAY:");
    for (const t of ctx.todaysTasks) {
      lines.push(`- [${t.priority}] ${t.title}${t.flagged ? " ⚠ flagged" : ""}`);
    }
  }

  if (ctx.flaggedAvoidance.length > 0) {
    lines.push("", "AVOIDING (Avoidance Radar):");
    for (const a of ctx.flaggedAvoidance) {
      lines.push(`- ${a.title} (flagged ${a.days_flagged}d)`);
    }
  }

  if (ctx.finance) {
    const f = ctx.finance;
    const fmt = (n: number) =>
      n.toLocaleString("en-US", {
        style: "currency",
        currency: "USD",
        maximumFractionDigits: 0,
      });
    lines.push("", "FINANCE SNAPSHOT (Plaid):");
    lines.push(
      `- Cash on hand: ${fmt(f.cashTotal)} · Debt remaining: ${fmt(f.debtTotal)} · Net liquid: ${fmt(f.netLiquid)}`
    );
    lines.push(
      `- Debt payoff progress: ${fmt(f.debtPaidOff)} of ${fmt(f.debtBaseline)} (${(f.debtPctPaid * 100).toFixed(1)}%)`
    );
    lines.push(
      `- 30-day flow: +${fmt(f.income30d)} in / -${fmt(f.burn30d)} out → net ${f.netFlow30d >= 0 ? "+" : ""}${fmt(f.netFlow30d)}`
    );
  }

  if (ctx.business) {
    const b = ctx.business;
    const fmt = (n: number) =>
      n.toLocaleString("en-US", {
        style: "currency",
        currency: "USD",
        maximumFractionDigits: 0,
      });
    lines.push("", "YLL BUSINESS (GoHighLevel):");
    lines.push(
      `- Revenue YTD: ${fmt(b.revenueYtd)} of ${fmt(b.revenueTarget)} (${(b.revenuePctToTarget * 100).toFixed(1)}%)`
    );
    lines.push(
      `- To hit $500K: need ${fmt(b.requiredDailyToHitTarget)}/day for the next ${b.daysLeftInYear} days (current pace: ${fmt(b.dailyRunRate)}/day → ${fmt(b.eoyProjection)} EOY)`
    );
    lines.push(
      `- Pipeline: ${fmt(b.pipelineValue)} across ${b.openCount} open ${b.openCount === 1 ? "deal" : "deals"}`
    );
    lines.push(
      `- This week: ${b.wonThisWeekCount} won (${fmt(b.wonThisWeekValue)}), ${b.newLeadsThisWeek} new ${b.newLeadsThisWeek === 1 ? "lead" : "leads"}`
    );
  }

  if (ctx.health) {
    const h = ctx.health;
    lines.push("", "HEALTH SNAPSHOT:");
    lines.push(
      `- TARGETS: ${HEALTH_GOALS.weight_lbs} lb, ${HEALTH_GOALS.steps_daily.toLocaleString()} steps/day, ${HEALTH_GOALS.sleep_hours_nightly} hr sleep/night, ${HEALTH_GOALS.workout_days_weekly}+ workouts/week`
    );
    if (h.weightLatest) {
      const toGo = (h.weightLatest.value - HEALTH_GOALS.weight_lbs).toFixed(1);
      const delta =
        h.weightDelta7d === null
          ? ""
          : ` (${h.weightDelta7d > 0 ? "+" : ""}${h.weightDelta7d} vs 7d ago)`;
      lines.push(
        `- Weight: ${h.weightLatest.value.toFixed(1)} ${h.weightLatest.unit ?? "lbs"}${delta} — ${toGo} lb to goal`
      );
    }
    const stepGap = HEALTH_GOALS.steps_daily - h.stepsToday;
    lines.push(
      `- Steps today: ${h.stepsToday.toLocaleString()} (7d avg ${h.stepsAvg7d.toLocaleString()}) — ${stepGap > 0 ? `${stepGap.toLocaleString()} to ${HEALTH_GOALS.steps_daily.toLocaleString()} goal` : "goal hit"}`
    );
    if (h.sleepLastNightHours !== null) {
      const sleepGap = +(HEALTH_GOALS.sleep_hours_nightly - h.sleepLastNightHours).toFixed(1);
      const avg =
        h.sleepAvg7dHours !== null ? ` (7d avg ${h.sleepAvg7dHours} hr)` : "";
      lines.push(
        `- Sleep last night: ${h.sleepLastNightHours.toFixed(1)} hr${avg} — ${sleepGap > 0 ? `${sleepGap} hr short of ${HEALTH_GOALS.sleep_hours_nightly} hr goal` : "goal hit"}`
      );
    }
    lines.push(
      `- Workouts (7d): ${h.workoutDays7d} day${h.workoutDays7d === 1 ? "" : "s"}, ${h.workoutMinutes7d} min — ${h.workoutDays7d >= HEALTH_GOALS.workout_days_weekly ? "goal hit" : `${HEALTH_GOALS.workout_days_weekly - h.workoutDays7d} more to hit ${HEALTH_GOALS.workout_days_weekly}+/wk goal`}`
    );
    if (h.rhrLatest !== null) {
      lines.push(`- Resting HR: ${h.rhrLatest} bpm`);
    }
  }

  if (ctx.recentCaptures.length > 0) {
    lines.push("", "RECENT CAPTURES (last 7d):");
    for (const c of ctx.recentCaptures.slice(0, 8)) {
      lines.push(`- [${c.source}] ${c.title ?? "(no title)"}`);
    }
  }

  if (ctx.weekStats) {
    lines.push("", "WEEK STATS:");
    lines.push(`- Tasks completed: ${ctx.weekStats.tasksCompleted}`);
    lines.push(`- Captures: ${ctx.weekStats.captures}`);
    lines.push(`- Reminders fired: ${ctx.weekStats.remindersFired}`);
  }

  if (ctx.monthStats) {
    lines.push("", "MONTH STATS:");
    lines.push(`- Tasks completed: ${ctx.monthStats.tasksCompleted}`);
    lines.push(`- Avg captures/day: ${ctx.monthStats.avgCapturesPerDay.toFixed(1)}`);
    lines.push(`- Active days: ${ctx.monthStats.longestStreak}`);
  }

  if (ctx.recentMemories.length > 0) {
    lines.push("", "REMEMBER ABOUT NALDO:");
    for (const m of ctx.recentMemories.slice(0, 5)) {
      lines.push(`- [${m.subject}] ${m.fact}`);
    }
  }

  lines.push("", "Generate the brief now.");
  return lines.join("\n");
}
